#!/bin/sh

while true
do
    bat_status=$(cat /sys/class/power_supply/BAT0/status)

    if [ bat_status = "Charging" ]
    then
	echo $bat_status
	sleep 6s
	continue
    fi

    if [ bat_status = "Discharging" ]
    then
	bat_capacity=$(cat /sys/class/power_supply/BAT0/capacity)

	if [ capacity == "17" ]
	then
	    notify-send -u critical "Battery Percentage" "Battery is critically low"
	    sleep 30s
	    continue
	fi
    fi

done
