#!/bin/sh
    
# current_volume=$(pactl get-sink-volume 0 | grep "[0-9]*%" | sed -e "s,.* \([0-9][0-9]*\)%.*,\1,")
current_volume="$(pactl list sinks | grep Volume | grep "[0-9]*%" | sed -e "s,.* \([0-9][0-9]*\)%.*,\1," | head -n 1)"

# increases volume only if it is lower than 100 percent
([ "$current_volume" -lt "100" ] && pactl set-sink-volume 0 +5% && \
     notify-send "Volume: $(expr $current_volume + 5)") || notify-send "Volume Full"
