#!/bin/sh

i=1;

for j in {1..10}
do
    i=$(( $i+1))
    printf "%4d\n" $i
done

# i=1; for j in {1..10}; do i=$(( $i+1)); n=$(printf "%04d\n" $i); echo "n=$n"; done;
# i=1; name_part="wall-"; for j in ~/pix/wall/*; do name=$name_part$(printf "%04d" $i); mv $j "$name.jpg"; i=$(($i+1)); done;
